/**
 * Icon Registry
 *
 * Maps icon names to their corresponding React components.
 * This file contains only the registry mapping, not the components themselves.
 */

import {
  PlusIcon,
  MinusIcon,
  CloseIcon,
  SearchIcon,
  EditIcon,
  DeleteIcon,
  SaveIcon,
  SettingsIcon,
  HomeIcon,
  UserIcon,
  EmailIcon,
  PhoneIcon,
  LockIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckIcon,
  WarningIcon,
  InfoIcon,
  HeartIcon,
  StarIcon,
  MenuIcon,
  MoreIcon,
  GroceriesIcon,
  RestaurantIcon,
  TransportIcon,
  EntertainmentIcon,
  HealthIcon,
  ShoppingIcon,
  UtilityIcon,
  TravelIcon,
  BuildingIcon,
  CameraIcon,
  MoneyIcon,
  WaterDropIcon,
  DocumentIcon,
  PaymentIcon,
  RefreshIcon,
} from './index'

// Icon registry - maps icon names to components
export const iconRegistry = {
  plus: PlusIcon,
  minus: MinusIcon,
  close: CloseIcon,
  search: SearchIcon,
  edit: EditIcon,
  delete: DeleteIcon,
  save: SaveIcon,
  settings: SettingsIcon,
  home: HomeIcon,
  user: UserIcon,
  email: EmailIcon,
  phone: PhoneIcon,
  lock: LockIcon,
  'arrow-up': ArrowUpIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  check: CheckIcon,
  warning: WarningIcon,
  info: InfoIcon,
  heart: HeartIcon,
  star: StarIcon,
  menu: MenuIcon,
  more: MoreIcon,
  groceries: GroceriesIcon,
  restaurant: RestaurantIcon,
  transport: TransportIcon,
  entertainment: EntertainmentIcon,
  health: HealthIcon,
  shopping: ShoppingIcon,
  utility: UtilityIcon,
  travel: TravelIcon,
  building: BuildingIcon,
  camera: CameraIcon,
  money: MoneyIcon,
  'water-drop': WaterDropIcon,
  document: DocumentIcon,
  payment: PaymentIcon,
  refresh: RefreshIcon,
} as const

// Type for available icon names
export type IconName = keyof typeof iconRegistry
